package cat.urv.utils;

public class Constants {
	final static public String kAnonymity = "k-anonymity";
	final static public String tCloseness = "t-closeness";
	final static public String splitting = "splitting";
	final static public String encryption = "encryption";
	final static public String coarsening = "coarsening";
	final static public String shift = "shift";
	final static public String microaggregation = "microaggregation";
	final static public String quasiIdentifier = "quasi_identifier";
	final static public String confidential = "confidential";
	final static public String identifier = "identifier";
	final static public String geometricObject = "geometric_object";
	final static public String numericDiscrete = "numeric_discrete";
	final static public String numericContinuous = "numeric_continuous";
	final static public String categoricOrdinal = "categoric_ordinal";
	final static public String categoric = "categoric";
	final static public String semantic = "semantic";
	final static public String ontology = "ontology";
	final static public String date = "date";
	final static public String type = "type";
	final static public String protection = "protection";
	final static public String k = "k";
	final static public String t = "t";
	final static public String clouds = "clouds";
	final static public String id_key = "id_key";
	final static public String radius = "radius";
	final static public String coarseningType = "coarsening_type";
	final static public String name = "name";
	final static public String dataType = "data_type";
	final static public String attributeType = "attribute_type";
	final static public String attribute = "attribute";
	final static public String non_confidential = "non_confidential";
	final static public String supression = "supression";
	final static public String not = "not";
	final static public int parameters_error = 0;
	final static public int tValueError = -2;
	final static public int kValueError = -1;
	final static public int k_anonymity = 1;
	final static public int t_Closeness = 2;
	final static public String dateFormat = "yyy/MM/dd";
	final static public String alphabetic = "alphabetic";
}
